### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Sanskriti-1711** [chinmaynehate/DFSpot-Deepfake-Recognition#9]
When I am trying to run this command:
python3 spot_deepfakes.py --media_type video --data_dir ../sample_videos/dfdc/fake/ --dataset dfdc --model TimmV2 TimmV2ST ViT ViTST  --model_dir ../models/ --video_id 0 1 2 --annotate True --device 0 --output_dir output/  

I am receiving the following error:
Traceback (most recent call last):
  File "/home/sanskriti/df_spot/DeepFake-Spot/src/spot_deepfakes.py", line 121, in <module>
    main()
  File "/home/sanskriti/df_spot/DeepFake-Spot/src/spot_deepfakes.py", line 99, in main
    predictions = utils.extract_predict_annotate(output_dir, ensemble_models, video_glob, video_idxs, transformer, blazeface_dir, device, models_loaded)
                 
  File "/home/sanskriti/df_spot/DeepFake-Spot/src/utils/utils.py", line 343, in extract_predict_annotate
    vid = cv2.VideoCapture(video_glob[ne])
                           ~~~~~~~~~~^^^^
IndexError: list index out of range

It is similar to the other datasets as well.

**Comment by twoBitSoda** [comment]
I know this response is too late to help you, but I found that you need to include --annotate True at the end of the bash command to fix this error. Why, I have no idea. My command looks like this:
python3 spot_deepfakes.py --media_type video --data_dir ../sample_videos/dfdc/fake/ --dataset dfdc --model TimmV2 TimmV2ST ViT ViTST --model_dir ../models --video_id 0  --annotate True
